//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENET_Care.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistCentre
    {
        public DistCentre()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.PackageStatus = new HashSet<PackageStatus>();
            this.PackageStatus1 = new HashSet<PackageStatus>();
        }
    
        public int CentreId { get; set; }
        public string CentreName { get; set; }
        public string CentreAddress { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<PackageStatus> PackageStatus { get; set; }
        public virtual ICollection<PackageStatus> PackageStatus1 { get; set; }
    }
}
