//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENET_Care.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageStatu
    {
        public int PackageStatusID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> SourceCentreID { get; set; }
        public Nullable<int> DestinationCentreID { get; set; }
        public Nullable<int> Status { get; set; }
        public string StaffID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DistCentre DistCentre { get; set; }
        public virtual DistCentre DistCentre1 { get; set; }
        public virtual Package Package { get; set; }
    }
}
